---
- name: Add user
  user:
    name: "{{ USER }}"
    shell: /bin/bash
    password: "{{ ansible_password }}"

- name: Add user to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{ USER }}"
    content: "{{ USER  }}  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key: user={{ USER }}
                     key={{ lookup('file', '/home/{{ USER }}/.ssh/id_rsa.pub') }}
                     state=present

- name: Disable Password Authentication
  lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

- name: Disable Root Login
  lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
  notify:
    - Restart ssh
